version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo "Would execute: Logging in to Amazon ECR..."
      - echo "Would execute: aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URL"
  build:
    commands:
      - echo "Would execute: Building Docker image..."
      - echo "Would execute: docker build -t $IMAGE_NAME -f src/backend/Dockerfile ."

  post_build:
    commands:
      - echo "Would execute: Tagging Docker image..."
      - echo "Would execute: docker tag $IMAGE_NAME:latest $ECR_REGISTRY_URL/$IMAGE_NAME:latest"
      - echo "Would execute: Pushing Docker image to ECR..."
      - echo "Would execute: docker push $ECR_REGISTRY_URL/$IMAGE_NAME:latest"

artifacts:
  files: '**/*'
  discard-paths: yes