version: 0.2

# These are passed from the CodeBuild project configuration in Terraform.
env:
  variables:
    AWS_ACCOUNT_ID: "$AWS_ACCOUNT_ID"       # Injected from CodeBuild project env
    AWS_DEFAULT_REGION: "$AWS_DEFAULT_REGION" # Injected from CodeBuild project env
    BACKEND_ECR_REPOSITORY_URI: "$BACKEND_ECR_REPOSITORY_URI" # Injected from CodeBuild project env
    FRONTEND_ECR_REPOSITORY_URI: "$FRONTEND_ECR_REPOSITORY_URI" # Injected from CodeBuild project env
    IMAGE_TAG: "latest" # Or use $CODEBUILD_RESOLVED_SOURCE_VERSION for a commit-specific tag

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      # Use the AWS CLI to get an authentication token and log in to ECR.
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      # --- Build Backend Image ---
      - echo "Building the backend Docker image from ./src/backend..."
      # Use the context and Dockerfile path specified in docker-compose.yaml
      - docker build -t $BACKEND_ECR_REPOSITORY_URI:$IMAGE_TAG -f ./src/backend/Dockerfile ./src/backend

      # --- Build Frontend Image ---
      - echo "Building the frontend Docker image from ./src/frontend..."
      # Use the context and Dockerfile path specified in docker-compose.yaml
      - docker build -t $FRONTEND_ECR_REPOSITORY_URI:$IMAGE_TAG -f ./src/frontend/Dockerfile ./src/frontend

  post_build:
    commands:
      # --- Push Backend Image to ECR ---
      - echo "Pushing the backend Docker image to ECR..."
      - docker push $BACKEND_ECR_REPOSITORY_URI:$IMAGE_TAG

      # --- Push Frontend Image to ECR ---
      - echo "Pushing the frontend Docker image to ECR..."
      - docker push $FRONTEND_ECR_REPOSITORY_URI:$IMAGE_TAG

      - echo "Build and push of backend and frontend images completed successfully!"

artifacts:
  files: []