name: streaming-explorer

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - public
    depends_on:
      - backend
      - frontend

      
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}
    networks:
      - public
      - private
    depends_on:
      - database_init

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - public
      - private
    environment:
      - BACKEND_URL=http://backend:8000

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    restart: always
    networks:
      - private
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  database_init:
    build:
      context: ./src/init
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}
    networks:
      - public
      - private
    depends_on:
      database:
        condition: service_healthy


# docker managed volumes
volumes:
  db_data:

networks:
  private:
    driver: bridge
    internal: true
  public:
    driver: bridge