name: streaming-explorer

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    networks:
      - private

  frontend:
    build:
      context: ./src/frontend
      dockerfile: ./Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - public
      - private
    environment:
      - BACKEND_URL=http://backend:8000

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - ./.env
    restart: always
    networks:
      - private
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

# docker managed volumes
volumes:
  db_data:
    name: db_data
    driver: local
    external: false

networks:
  private:
    name: private
    driver: bridge
    attachable: false
    internal: true
  public:
    name: public
    driver: bridge
    attachable: false
    internal: false