
# Define variables

STREAMLIT_APP = src/frontend/home.py
FASTAPI_APP = src/backend/app.py

.PHONY: frontend

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

format: ## Run pre-commit hooks
	pre-commit run -a

test-full: ## Run all tests
	pytest

# Run the Streamlit application
frontend:
	streamlit run $(STREAMLIT_APP)

# Run the fastapi server
backend:
	python $(FASTAPI_APP)
